mcc: "208"                 
mnc: "95"   

eutraBand: "7"             
downlinkFrequency: "2685000000L"    
uplinkFrequencyOffset: "-120000000"
NumberRbDl: "25"
MaxRxGain: "110"
ParallelConfig: "PARALLEL_SINGLE_THREAD"

configurationPathofCN: "/var/snap/oai-cn/current/"
configurationPathofRAN: "/var/snap/oai-ran/current/"
snapBinaryPath: "/snap/bin/"
hssDomainName: "oaicn"
mmeDomainName: "oaicn"
spgwDomainName: "oaicn"
mysqlDomainName: "mysql"
dns: "192.168.106.12"

flexRAN: false
flexRANDomainName: "flexran"
test: false
