mcc: "208"                 
mnc: "95"   

eutraBand: "7"             
downlinkFrequency: "2685000000L"    
uplinkFrequencyOffset: "-120000000"
NumberRbDl: "25"
MaxRxGain: "110"
ParallelConfig: "PARALLEL_SINGLE_THREAD"

configurationPathofCN: "/var/snap/oai-cn/current/"
configurationPathofRAN: "/var/snap/oai-ran/current/"
snapBinaryPath: "/snap/bin/"
hssDomainName: "oaihss"
mmeDomainName: "oaimme"
spgwDomainName: "oaispgw"
mysqlDomainName: "mysql"
dns: "192.168.1.1"

flexRAN: false
flexRANDomainName: "flexran"
test: false
