version: '2'

services:
  mysql:
    image: mysql:5.6
    restart: always
    container_name: mysql
    environment: # shell variables
      - MYSQL_ROOT_PASSWORD=linux
    networks:
      - oai
  oaihss: # Domain name of container
    image: mosaic5gecosys/oaihss:mytest
    restart: always # Operation Policy
    container_name: oaihss # Name of the container
    hostname: ubuntu # hostname
    privileged: true # Give the container the permission to manipulate the host
    depends_on: # Before starting this container, what should be ready
      - "mysql"
    volumes: # Mounted from host
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
      - /lib/modules:/lib/modules:ro
      - ./conf.yaml:/root/config/conf.yaml:ro
      # - /home/cigarier/mosaic5g/kube5g/dockers/docker-hook:/root/docker-hook:rw
    networks: # the network this container attached to
      - oai
  oaimme: # Domain name of container
    image: mosaic5gecosys/oaimme:mytest
    restart: always # Operation Policy
    container_name: oaimme # Name of the container
    hostname: ubuntu # hostname
    privileged: true # Give the container the permission to manipulate the host
    depends_on: # Before starting this container, what should be ready
      - "mysql"
      - "oaihss"
      - "oaispgw"
    volumes: # Mounted from host
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
      - /lib/modules:/lib/modules:ro
      - ./conf.yaml:/root/config/conf.yaml:ro
      # - /home/cigarier/mosaic5g/kube5g/dockers/docker-hook:/root/docker-hook:rw
    networks: # the network this container attached to
      - oai
  oaispgw: # Domain name of container
    image: mosaic5gecosys/oaispgw:mytest
    restart: always # Operation Policy
    container_name: oaispgw # Name of the container
    hostname: ubuntu # hostname
    privileged: true # Give the container the permission to manipulate the host
    depends_on: # Before starting this container, what should be ready
      - "mysql"
      - "oaihss"
    volumes: # Mounted from host
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
      - /lib/modules:/lib/modules:ro
      - ./conf.yaml:/root/config/conf.yaml:ro
      # - /home/cigarier/mosaic5g/kube5g/dockers/docker-hook:/root/docker-hook:rw
    networks: # the network this container attached to
      - oai
  # oaicn: # Domain name of container
  #   image: mosaic5gecosys/oaicn:mytest # 1.0 image of the container
  #   restart: always # Operation Policy
  #   container_name: oaicn # Name of the container
  #   hostname: ubuntu # hostname
  #   privileged: true # Give the container the permission to manipulate the host
  #   depends_on: # Before starting this container, what should be ready
  #     - "mysql"
  #   # cap_add:
  #   #   - SYS_ADMIN
  #   volumes: # Mounted from host
  #     - /sys/fs/cgroup:/sys/fs/cgroup:ro
  #     - /lib/modules:/lib/modules:ro
  #     - ./conf.yaml:/root/config/conf.yaml:ro
  #   networks: # the network this container attached to
  #     - oai
  oairan:
    image: mosaic5gecosys/oairan:mytest
    restart: always
    container_name: oairan
    hostname: oairan
    privileged: true
    depends_on:
      - "mysql"
      - "oaihss"
      - "oaimme"
      - "oaispgw"
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
      - /lib/modules:/lib/modules:ro
      - /dev/bus/usb:/dev/bus/usb
      - ./conf.yaml:/root/config/conf.yaml:ro
      # - /home/cigarier/mosaic5g/kube5g/dockers/docker-hook:/root/docker-hook:rw
    networks:
      - oai

networks: # Define our network here
  oai:
    driver: bridge
    driver_opts:
      com.docker.network.driver.mtu: 9000 # Configure mtu
